# Generated by scripts/generate-openapi.ts. Do not edit.
from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict

class CreateRun(TypedDict):
    agent: str
    workspace: str
    session: NotRequired[str]
    input: str
    budget: NotRequired[dict[str, Any]]

class RunBudgetOverrides(TypedDict):
    maxTurns: NotRequired[int]
    maxToolCalls: NotRequired[int]
    maxInputTokens: NotRequired[int]
    maxOutputTokens: NotRequired[int]
    maxCostUsd: NotRequired[float]
    totalTimeoutMs: NotRequired[int]
    modelIdleTimeoutMs: NotRequired[int]
    commandTimeoutMs: NotRequired[int]

class CreateAgent(TypedDict):
    id: NotRequired[str]
    name: str
    instructions: NotRequired[str]
    modelCapabilities: NotRequired[list[str | str | str | str | str | str]]
    allowedTools: NotRequired[list[str]]
    defaultBudget: NotRequired[dict[str, Any]]

class CreateWorkspace(TypedDict):
    id: NotRequired[str]
    mode: NotRequired[str]

class InboundEnvelope(TypedDict):
    deliveryId: str
    senderExternalId: str
    conversationExternalId: NotRequired[str]
    threadExternalId: NotRequired[str]
    text: str
    attachmentUrls: NotRequired[list[str]]
    receivedAt: NotRequired[str]

class Error(TypedDict):
    error: NotRequired[dict[str, Any]]

class ErrorEnvelope(TypedDict):
    error: dict[str, Any]

class MintRunToken(TypedDict):
    scopes: list[str]
    ttlSeconds: NotRequired[int]
    agentId: NotRequired[str]
    workspaceId: NotRequired[str]
    budgetCeiling: NotRequired[dict[str, Any]]

class MintRunTokenResponse(TypedDict):
    token: str
    tokenId: str
    expiresAt: str
    scopes: list[str]
    replayPolicy: str

class RevokeTokenResponse(TypedDict):
    tokenId: str
    revoked: bool

class PublishArtifact(TypedDict):
    path: str
    mediaType: str

API_OPERATIONS: tuple[tuple[str, str, str], ...] = (
    ("GET", "/healthz", "getHealthz"),
    ("POST", "/hooks/webhook/{accountId}", "postHooksWebhookByAccountId"),
    ("GET", "/readyz", "getReadyz"),
    ("GET", "/v1/agents", "getV1Agents"),
    ("POST", "/v1/agents", "postV1Agents"),
    ("GET", "/v1/agents/{agentId}", "getV1AgentsByAgentId"),
    ("POST", "/v1/approvals/{approvalId}", "postV1ApprovalsByApprovalId"),
    ("GET", "/v1/artifacts/{artifactId}", "getV1ArtifactsByArtifactId"),
    ("POST", "/v1/runs", "postV1Runs"),
    ("GET", "/v1/runs/{runId}", "getV1RunsByRunId"),
    ("POST", "/v1/runs/{runId}/artifacts", "postV1RunsByRunIdArtifacts"),
    ("GET", "/v1/runs/{runId}/attempts", "getV1RunsByRunIdAttempts"),
    ("POST", "/v1/runs/{runId}/cancel", "postV1RunsByRunIdCancel"),
    ("GET", "/v1/runs/{runId}/children", "getV1RunsByRunIdChildren"),
    ("GET", "/v1/runs/{runId}/events", "getV1RunsByRunIdEvents"),
    ("POST", "/v1/runs/{runId}/steer", "postV1RunsByRunIdSteer"),
    ("GET", "/v1/sessions/{sessionId}", "getV1SessionsBySessionId"),
    ("GET", "/v1/sessions/{sessionId}/messages", "getV1SessionsBySessionIdMessages"),
    ("POST", "/v1/tokens", "postV1Tokens"),
    ("DELETE", "/v1/tokens/{tokenId}", "deleteV1TokensByTokenId"),
    ("GET", "/v1/workspaces", "getV1Workspaces"),
    ("POST", "/v1/workspaces", "postV1Workspaces"),
    ("GET", "/v1/workspaces/{workspaceId}", "getV1WorkspacesByWorkspaceId"),
)

__all__ = ["CreateRun","RunBudgetOverrides","CreateAgent","CreateWorkspace","InboundEnvelope","Error","ErrorEnvelope","MintRunToken","MintRunTokenResponse","RevokeTokenResponse","PublishArtifact","API_OPERATIONS"]
