# Generated by scripts/generate-openapi.ts. Do not edit.
from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict

class AgentListResponse(TypedDict):
    agents: list[AgentProfileRecord]

AgentModelCapability: TypeAlias = Literal["text", "tools", "vision", "json", "reasoning", "delegated-agent"]

class AgentProfileRecord(TypedDict):
    id: str
    version: int
    appId: str
    tenantId: str
    userId: str
    name: str
    instructions: str
    modelCapabilities: list[AgentModelCapability]
    allowedTools: list[str]
    defaultBudget: RunBudget
    createdAt: str

class ApprovalRecord(TypedDict):
    id: str
    runId: str
    toolCallId: str
    toolName: str
    toolArgumentsDigest: str
    executionDigest: str
    appId: str
    tenantId: str
    userId: str
    workspaceId: str
    policyGeneration: int
    routeGeneration: str
    status: ApprovalStatus
    expiresAt: str
    createdAt: str
    resolvedAt: NotRequired[str]

ApprovalStatus: TypeAlias = Literal["PENDING", "APPROVED", "DENIED", "EXPIRED"]

class ArtifactPayloadResponse(TypedDict):
    record: ArtifactRecord
    dataBase64: str

class ArtifactRecord(TypedDict):
    id: str
    runId: str
    appId: str
    tenantId: str
    userId: str
    workspaceId: str
    path: str
    mediaType: str
    sizeBytes: int
    sha256: str
    createdAt: str

class ChildRunsResponse(TypedDict):
    runs: list[RunRecord]

class CreateAgent(TypedDict):
    id: NotRequired[str]
    name: str
    instructions: NotRequired[str]
    modelCapabilities: NotRequired[list[AgentModelCapability]]
    allowedTools: NotRequired[list[str]]
    defaultBudget: NotRequired[RunBudgetOverrides]

class CreateRun(TypedDict):
    agent: str
    workspace: str
    session: NotRequired[str]
    input: str
    budget: NotRequired[RunBudgetOverrides]

class CreateRunResponse(TypedDict):
    runId: str
    status: RunStatus
    eventCursor: int
    idempotentReplay: bool

class CreateWorkspace(TypedDict):
    id: NotRequired[str]
    mode: NotRequired[Literal["managed"]]

ErrorDetail: TypeAlias = dict[str, Any]

class ErrorEnvelope(TypedDict):
    error: StructuredError

class GatewayHealth(TypedDict):
    ok: Literal[True]
    role: Literal["gateway"]
    uptimeSeconds: int
    rssBytes: int

class GatewayReadinessDependencies(TypedDict):
    manager: ManagerReadiness

class GatewayReadiness(TypedDict):
    ok: bool
    role: Literal["gateway"]
    dependencies: GatewayReadinessDependencies

class InboundEnvelope(TypedDict):
    deliveryId: str
    senderExternalId: str
    conversationExternalId: NotRequired[str]
    threadExternalId: NotRequired[str]
    text: str
    attachmentUrls: NotRequired[list[str]]
    receivedAt: NotRequired[str]

class ManagerReadiness(TypedDict):
    ok: bool
    role: Literal["manager"]
    protocolVersion: Literal["1"]
    dependencies: dict[str, ReadinessDependency]

class MintRunToken(TypedDict):
    scopes: list[str]
    ttlSeconds: NotRequired[int]
    agentId: NotRequired[str]
    workspaceId: NotRequired[str]
    budgetCeiling: NotRequired[RunBudgetOverrides]

class MintRunTokenResponse(TypedDict):
    token: str
    tokenId: str
    expiresAt: str
    scopes: list[str]
    replayPolicy: Literal["resource_bound_multi_use"]

class PublishArtifact(TypedDict):
    path: str
    mediaType: str

class RevokeTokenResponse(TypedDict):
    tokenId: str
    revoked: Literal[True]

class ReadinessDependency(TypedDict):
    ok: bool
    reason: NotRequired[str]

class ResolveApproval(TypedDict):
    approved: bool

class RunAttemptRecord(TypedDict):
    id: str
    runId: str
    attempt: int
    status: Literal["RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", "TIMED_OUT", "ORPHANED"]
    startedAt: str
    endedAt: NotRequired[str]

class RunAttemptsResponse(TypedDict):
    attempts: list[RunAttemptRecord]

class RunBudget(TypedDict):
    maxTurns: int
    maxToolCalls: int
    maxInputTokens: int
    maxOutputTokens: int
    maxCostUsd: float
    totalTimeoutMs: int
    modelIdleTimeoutMs: int
    commandTimeoutMs: int

class RunBudgetOverrides(TypedDict):
    maxTurns: NotRequired[int]
    maxToolCalls: NotRequired[int]
    maxInputTokens: NotRequired[int]
    maxOutputTokens: NotRequired[int]
    maxCostUsd: NotRequired[float]
    totalTimeoutMs: NotRequired[int]
    modelIdleTimeoutMs: NotRequired[int]
    commandTimeoutMs: NotRequired[int]

class RunEvent(TypedDict):
    runId: str
    sequence: int
    type: RunEventType
    payload: ErrorDetail
    createdAt: str

RunEventType: TypeAlias = Literal["run.accepted", "run.queued", "run.preparing", "run.started", "run.snapshot.frozen", "run.checkpointing", "run.timed_out", "run.steered", "agent.message.delta", "agent.message.completed", "tool.call.requested", "tool.call.completed", "usage.updated", "workspace.lease.acquired", "workspace.lease.released", "workspace.restore.started", "workspace.restore.completed", "workspace.checkpoint.completed", "workspace.checkpoint.failed", "approval.requested", "approval.resolved", "artifact.created", "subagent.started", "subagent.completed", "run.succeeded", "run.failed", "run.cancelled", "run.orphaned"]

class RunRecord(TypedDict):
    id: str
    idempotencyKey: str
    appId: str
    tenantId: str
    userId: str
    agentId: str
    workspaceId: str
    sessionId: NotRequired[str]
    parentRunId: NotRequired[str]
    depth: int
    deliveryAllowed: bool
    input: str
    budget: RunBudget
    usage: RunUsage
    status: RunStatus
    lastSequence: int
    errorCode: NotRequired[str]
    errorMessage: NotRequired[str]
    createdAt: str
    updatedAt: str

RunStatus: TypeAlias = Literal["ACCEPTED", "QUEUED", "PREPARING", "RUNNING", "CHECKPOINTING", "SUCCEEDED", "FAILED", "CANCELLED", "TIMED_OUT", "ORPHANED"]

class RunStreamError(TypedDict):
    message: str

RunStreamFrame: TypeAlias = RunEvent | RunStreamError

class RunUsage(TypedDict):
    inputTokens: int
    outputTokens: int
    costUsd: float
    toolCalls: int

class SessionMessageRecord(TypedDict):
    id: str
    sessionId: str
    runId: NotRequired[str]
    role: SessionMessageRole
    content: str
    metadata: ErrorDetail
    createdAt: str

SessionMessageRole: TypeAlias = Literal["system", "user", "assistant", "tool"]

class SessionMessagesResponse(TypedDict):
    messages: list[SessionMessageRecord]

class SessionRecord(TypedDict):
    id: str
    appId: str
    tenantId: str
    userId: str
    agentId: str
    createdAt: str
    updatedAt: str

class SteerRun(TypedDict):
    instruction: str

class StructuredError(TypedDict):
    version: Literal[1]
    code: str
    message: str
    retryable: bool
    retryAfterMs: NotRequired[int]
    details: NotRequired[ErrorDetail]

class WebhookIngestResponse(TypedDict):
    duplicate: bool
    runId: NotRequired[str]

class WorkspaceListResponse(TypedDict):
    workspaces: list[WorkspaceRecord]

class WorkspaceRecord(TypedDict):
    id: str
    appId: str
    tenantId: str
    userId: str
    mode: Literal["managed", "registered-bind"]
    state: Literal["WARM", "COLD", "RESTORING", "IN_USE", "SNAPSHOTTING", "CORRUPT", "ERROR"]
    registeredPath: NotRequired[str]
    createdAt: str
    updatedAt: str

API_OPERATIONS: tuple[tuple[str, str, str], ...] = (
    ("GET", "/healthz", "getHealthz"),
    ("POST", "/hooks/webhook/{accountId}", "postHooksWebhookByAccountId"),
    ("GET", "/readyz", "getReadyz"),
    ("GET", "/v1/agents", "getV1Agents"),
    ("POST", "/v1/agents", "postV1Agents"),
    ("GET", "/v1/agents/{agentId}", "getV1AgentsByAgentId"),
    ("POST", "/v1/approvals/{approvalId}", "postV1ApprovalsByApprovalId"),
    ("GET", "/v1/artifacts/{artifactId}", "getV1ArtifactsByArtifactId"),
    ("POST", "/v1/runs", "postV1Runs"),
    ("GET", "/v1/runs/{runId}", "getV1RunsByRunId"),
    ("POST", "/v1/runs/{runId}/artifacts", "postV1RunsByRunIdArtifacts"),
    ("GET", "/v1/runs/{runId}/attempts", "getV1RunsByRunIdAttempts"),
    ("POST", "/v1/runs/{runId}/cancel", "postV1RunsByRunIdCancel"),
    ("GET", "/v1/runs/{runId}/children", "getV1RunsByRunIdChildren"),
    ("GET", "/v1/runs/{runId}/events", "getV1RunsByRunIdEvents"),
    ("POST", "/v1/runs/{runId}/steer", "postV1RunsByRunIdSteer"),
    ("GET", "/v1/sessions/{sessionId}", "getV1SessionsBySessionId"),
    ("GET", "/v1/sessions/{sessionId}/messages", "getV1SessionsBySessionIdMessages"),
    ("POST", "/v1/tokens", "postV1Tokens"),
    ("DELETE", "/v1/tokens/{tokenId}", "deleteV1TokensByTokenId"),
    ("GET", "/v1/workspaces", "getV1Workspaces"),
    ("POST", "/v1/workspaces", "postV1Workspaces"),
    ("GET", "/v1/workspaces/{workspaceId}", "getV1WorkspacesByWorkspaceId"),
)

__all__ = ["AgentListResponse","AgentModelCapability","AgentProfileRecord","ApprovalRecord","ApprovalStatus","ArtifactPayloadResponse","ArtifactRecord","ChildRunsResponse","CreateAgent","CreateRun","CreateRunResponse","CreateWorkspace","ErrorDetail","ErrorEnvelope","GatewayHealth","GatewayReadinessDependencies","GatewayReadiness","InboundEnvelope","ManagerReadiness","MintRunToken","MintRunTokenResponse","PublishArtifact","RevokeTokenResponse","ReadinessDependency","ResolveApproval","RunAttemptRecord","RunAttemptsResponse","RunBudget","RunBudgetOverrides","RunEvent","RunEventType","RunRecord","RunStatus","RunStreamError","RunStreamFrame","RunUsage","SessionMessageRecord","SessionMessageRole","SessionMessagesResponse","SessionRecord","SteerRun","StructuredError","WebhookIngestResponse","WorkspaceListResponse","WorkspaceRecord","API_OPERATIONS"]
