import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  AUTHENTICATED_OPERATION_METHODS,
  AUTHENTICATED_OPERATION_ROUTES,
  GENERATED_API_OPERATIONS,
  GENERATED_API_SCHEMAS,
  LiteHarnessClient,
} from "@lite-harness/sdk";
import { InboundEnvelopeSchema } from "@lite-harness/contracts";
import { normalizeInbound } from "@lite-harness/integrations";

const root = resolve(import.meta.dirname, "..");
const document = JSON.parse(readFileSync(resolve(root, "docs/openapi.json"), "utf8")) as {
  openapi: string;
  components: { schemas: Record<string, unknown> };
  paths: Record<string, Record<string, any>>;
};
const pythonGenerated = readFileSync(resolve(root, "sdks/python/src/lite_harness/generated_api.py"), "utf8");

describe("authoritative OpenAPI and generated SDK contract", () => {
  it("has a typed success response and request model for every public operation", () => {
    expect(document.openapi).toMatch(/^3\.1\./);
    for (const [path, pathItem] of Object.entries(document.paths)) {
      for (const [method, operation] of Object.entries(pathItem)) {
        if (!["get", "post", "put", "patch", "delete"].includes(method)) continue;
        expect(operation.operationId, `${method.toUpperCase()} ${path} operationId`).toMatch(/^[A-Za-z][A-Za-z0-9]+$/);
        const successResponses = (Object.entries(operation.responses ?? {}) as Array<[string, Record<string, any>]>).filter(([status]) => /^2\d\d$/.test(status));
        expect(successResponses.length, `${method.toUpperCase()} ${path} success response`).toBeGreaterThan(0);
        for (const [status, response] of successResponses) {
          const content = response.content ?? {};
          const media = content["application/json"] ?? content["text/event-stream"];
          expect(media?.schema?.$ref, `${method.toUpperCase()} ${path} ${status} schema`).toMatch(/^#\/components\/schemas\/[A-Za-z][A-Za-z0-9]+$/);
          const schemaName = String(media.schema.$ref).split("/").at(-1) as string;
          expect(document.components.schemas, `${schemaName} component`).toHaveProperty(schemaName);
        }
        const defaultError = operation.responses?.default?.content?.["application/json"]?.schema?.$ref;
        expect(defaultError, `${method.toUpperCase()} ${path} default error schema`).toBe("#/components/schemas/ErrorEnvelope");
        if (path.startsWith("/v1/")) {
          for (const status of ["401", "403", "429"]) {
            expect(operation.responses?.[status]?.content?.["application/json"]?.schema?.$ref, `${method.toUpperCase()} ${path} ${status} schema`).toBe("#/components/schemas/ErrorEnvelope");
          }
        }
        if (operation.requestBody) {
          expect(operation.requestBody.content?.["application/json"]?.schema?.$ref, `${method.toUpperCase()} ${path} request schema`).toMatch(/^#\/components\/schemas\//);
        }
        for (const parameter of operation.parameters ?? []) {
          if (parameter.in === "path") expect(parameter.required, `${method.toUpperCase()} ${path} ${parameter.name}`).toBe(true);
        }
      }
    }
  });

  it("keeps TypeScript and Python generated model/operation inventories in parity", () => {
    const schemaNames = Object.keys(document.components.schemas);
    expect([...GENERATED_API_SCHEMAS]).toEqual(schemaNames);
    expect(pythonGenerated).toContain("# Generated by scripts/generate-openapi.ts. Do not edit.");
    const pythonExports = JSON.parse(pythonGenerated.match(/__all__ = (\[[\s\S]*?\])/)?.[1] ?? "[]") as string[];
    expect(pythonExports).toEqual([...schemaNames, "API_OPERATIONS"]);

    const openApiOperations = Object.entries(document.paths).flatMap(([path, item]) =>
      Object.entries(item)
        .filter(([method]) => ["get", "post", "put", "patch", "delete"].includes(method))
        .map(([method, operation]) => ({ method: method.toUpperCase(), path, operationId: operation.operationId })),
    ).sort((left, right) => `${left.path}:${left.method}`.localeCompare(`${right.path}:${right.method}`));
    expect([...GENERATED_API_OPERATIONS]).toEqual(openApiOperations);
    const pythonOperations = [...pythonGenerated.matchAll(/^\s+\("([A-Z]+)", "([^"]+)", "([^"]+)"\),$/gm)]
      .map((match) => ({ method: match[1], path: match[2], operationId: match[3] }));
    expect(pythonOperations).toEqual(openApiOperations);
    expect(pythonGenerated).toContain("class GatewayReadinessDependencies(TypedDict):\n    manager: ManagerReadiness");
    expect(pythonGenerated).toContain("class GatewayReadiness(TypedDict):\n    ok: bool\n    role: Literal[\"gateway\"]\n    dependencies: GatewayReadinessDependencies");
    expect(pythonGenerated).toContain("class ManagerReadiness(TypedDict):");
    expect(pythonGenerated).toContain("dependencies: dict[str, ReadinessDependency]");
    for (const name of schemaNames) expect(pythonGenerated).toMatch(new RegExp(`(?:class|^${name}:)`, "m"));
  });

  it("maps every authenticated OpenAPI operation to a callable TypeScript SDK method", () => {
    const expectedMethods = {
      getV1Agents: "listAgents",
      postV1Agents: "createAgent",
      getV1AgentsByAgentId: "getAgent",
      postV1ApprovalsByApprovalId: "resolveApproval",
      getV1ArtifactsByArtifactId: "downloadArtifact",
      postV1Runs: "createRun",
      getV1RunsByRunId: "getRun",
      postV1RunsByRunIdArtifacts: "publishArtifact",
      getV1RunsByRunIdAttempts: "getRunAttempts",
      postV1RunsByRunIdCancel: "cancelRun",
      getV1RunsByRunIdChildren: "getChildRuns",
      getV1RunsByRunIdEvents: "events",
      postV1RunsByRunIdSteer: "steerRun",
      getV1SessionsBySessionId: "getSession",
      getV1SessionsBySessionIdMessages: "getSessionMessages",
      postV1Tokens: "mintRunToken",
      deleteV1TokensByTokenId: "revokeToken",
      getV1Workspaces: "listWorkspaces",
      postV1Workspaces: "createWorkspace",
      getV1WorkspacesByWorkspaceId: "getWorkspace",
    } as const;
    expect(AUTHENTICATED_OPERATION_METHODS).toEqual(expectedMethods);
    const expected = GENERATED_API_OPERATIONS
      .filter((operation) => operation.path.startsWith("/v1/"))
      .map((operation) => [
        operation.method,
        operation.path,
        operation.operationId,
        expectedMethods[operation.operationId as keyof typeof expectedMethods],
      ]);
    expect(AUTHENTICATED_OPERATION_ROUTES).toEqual(expected);
    expect(expected).toHaveLength(20);
    for (const methodName of Object.values(expectedMethods)) {
      expect(typeof LiteHarnessClient.prototype[methodName]).toBe("function");
    }
  });

  it("keeps Python generated annotations introspectable", () => {
    execFileSync("python", ["-c", [
      "import importlib, typing",
      "module = importlib.import_module('lite_harness.generated_api')",
      "for name in module.__all__:",
      "    value = getattr(module, name)",
      "    if isinstance(value, type) and hasattr(value, '__annotations__'):",
      "        typing.get_type_hints(value, vars(module), vars(module))",
    ].join("\n")], {
      cwd: root,
      env: { ...process.env, PYTHONPATH: resolve(root, "sdks/python/src") },
      stdio: "pipe",
    });
  });

  it("keeps webhook contract and runtime normalization aligned", () => {
    const body = {
      deliveryId: "delivery-1",
      senderExternalId: "sender-1",
      text: "\nhello",
      receivedAt: "Wed, 15 Jul 2026 16:00:00 GMT",
      providerMetadata: { source: "fixture" },
    };
    expect(InboundEnvelopeSchema.additionalProperties).toBe(true);
    expect(InboundEnvelopeSchema.properties.receivedAt).not.toHaveProperty("format");
    expect(InboundEnvelopeSchema.properties.text.pattern).toContain("\\S");
    expect(normalizeInbound({ ...body, connectorId: "webhook", accountId: "primary" })).toMatchObject({
      deliveryId: "delivery-1",
      text: "\nhello",
    });

    const invalid = { ...body, receivedAt: 42 };
    expect(() => normalizeInbound({ ...invalid, connectorId: "webhook", accountId: "primary" })).toThrow("receivedAt");
  });
});
