import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { GENERATED_API_OPERATIONS, GENERATED_API_SCHEMAS } from "@lite-harness/sdk";

const root = resolve(import.meta.dirname, "..");
const document = JSON.parse(readFileSync(resolve(root, "docs/openapi.json"), "utf8")) as {
  openapi: string;
  components: { schemas: Record<string, unknown> };
  paths: Record<string, Record<string, any>>;
};
const pythonGenerated = readFileSync(resolve(root, "sdks/python/src/lite_harness/generated_api.py"), "utf8");

describe("authoritative OpenAPI and generated SDK contract", () => {
  it("has a typed success response and request model for every public operation", () => {
    expect(document.openapi).toMatch(/^3\.1\./);
    for (const [path, pathItem] of Object.entries(document.paths)) {
      for (const [method, operation] of Object.entries(pathItem)) {
        if (!["get", "post", "put", "patch", "delete"].includes(method)) continue;
        expect(operation.operationId, `${method.toUpperCase()} ${path} operationId`).toMatch(/^[A-Za-z][A-Za-z0-9]+$/);
        const successResponses = (Object.entries(operation.responses ?? {}) as Array<[string, Record<string, any>]>).filter(([status]) => /^2\d\d$/.test(status));
        expect(successResponses.length, `${method.toUpperCase()} ${path} success response`).toBeGreaterThan(0);
        for (const [status, response] of successResponses) {
          const content = response.content ?? {};
          const media = content["application/json"] ?? content["text/event-stream"];
          expect(media?.schema?.$ref, `${method.toUpperCase()} ${path} ${status} schema`).toMatch(/^#\/components\/schemas\/[A-Za-z][A-Za-z0-9]+$/);
          const schemaName = String(media.schema.$ref).split("/").at(-1) as string;
          expect(document.components.schemas, `${schemaName} component`).toHaveProperty(schemaName);
        }
        if (operation.requestBody) {
          expect(operation.requestBody.content?.["application/json"]?.schema?.$ref, `${method.toUpperCase()} ${path} request schema`).toMatch(/^#\/components\/schemas\//);
        }
        for (const parameter of operation.parameters ?? []) {
          if (parameter.in === "path") expect(parameter.required, `${method.toUpperCase()} ${path} ${parameter.name}`).toBe(true);
        }
      }
    }
  });

  it("keeps TypeScript and Python generated model/operation inventories in parity", () => {
    const schemaNames = Object.keys(document.components.schemas);
    expect([...GENERATED_API_SCHEMAS]).toEqual(schemaNames);
    expect(pythonGenerated).toContain("# Generated by scripts/generate-openapi.ts. Do not edit.");
    const pythonExports = JSON.parse(pythonGenerated.match(/__all__ = (\[[\s\S]*?\])/)?.[1] ?? "[]") as string[];
    expect(pythonExports).toEqual([...schemaNames, "API_OPERATIONS"]);

    const openApiOperations = Object.entries(document.paths).flatMap(([path, item]) =>
      Object.entries(item)
        .filter(([method]) => ["get", "post", "put", "patch", "delete"].includes(method))
        .map(([method, operation]) => ({ method: method.toUpperCase(), path, operationId: operation.operationId })),
    ).sort((left, right) => `${left.path}:${left.method}`.localeCompare(`${right.path}:${right.method}`));
    expect([...GENERATED_API_OPERATIONS]).toEqual(openApiOperations);
    const pythonOperations = [...pythonGenerated.matchAll(/^\s+\("([A-Z]+)", "([^"]+)", "([^"]+)"\),$/gm)]
      .map((match) => ({ method: match[1], path: match[2], operationId: match[3] }));
    expect(pythonOperations).toEqual(openApiOperations);
    for (const name of schemaNames) expect(pythonGenerated).toMatch(new RegExp(`(?:class|^${name}:)`, "m"));
  });
});
