/* Generated by scripts/generate-openapi.ts. Do not edit. */
export type AgentListResponse =
{
  agents: Array<AgentProfileRecord>;
};
export type AgentModelCapability = "text" | "tools" | "vision" | "json" | "reasoning" | "delegated-agent";
export type AgentProfileRecord =
{
  id: string;
  version: number;
  appId: string;
  tenantId: string;
  userId: string;
  name: string;
  instructions: string;
  modelCapabilities: Array<AgentModelCapability>;
  allowedTools: Array<string>;
  defaultBudget: RunBudget;
  createdAt: string;
};
export type ApprovalRecord =
{
  id: string;
  runId: string;
  toolCallId: string;
  toolName: string;
  toolArgumentsDigest: string;
  executionDigest: string;
  appId: string;
  tenantId: string;
  userId: string;
  workspaceId: string;
  policyGeneration: number;
  routeGeneration: string;
  status: ApprovalStatus;
  expiresAt: string;
  createdAt: string;
  resolvedAt?: string;
};
export type ApprovalStatus = "PENDING" | "APPROVED" | "DENIED" | "EXPIRED";
export type ArtifactPayloadResponse =
{
  record: ArtifactRecord;
  dataBase64: string;
};
export type ArtifactRecord =
{
  id: string;
  runId: string;
  appId: string;
  tenantId: string;
  userId: string;
  workspaceId: string;
  path: string;
  mediaType: string;
  sizeBytes: number;
  sha256: string;
  createdAt: string;
};
export type ChildRunsResponse =
{
  runs: Array<RunRecord>;
};
export type CreateAgent =
{
  id?: string;
  name: string;
  instructions?: string;
  modelCapabilities?: Array<AgentModelCapability>;
  allowedTools?: Array<string>;
  defaultBudget?: RunBudgetOverrides;
};
export type CreateRun =
{
  agent: string;
  workspace: string;
  session?: string;
  providerConnectionId?: string;
  input: string;
  budget?: RunBudgetOverrides;
};
export type CreateRunResponse =
{
  runId: string;
  status: RunStatus;
  eventCursor: number;
  idempotentReplay: boolean;
};
export type CreateProviderConnection =
{
  id?: string;
  providerId: string;
  displayName: string;
  authKind?: "api_key" | "oauth" | "delegated_cli" | "local_endpoint";
  baseUrl?: string;
  modelIds?: Array<string>;
};
export type CreateWorkspace =
{
  id?: string;
  mode?: "managed";
};
export type DeleteProviderConnectionResponse =
{
  connectionId: string;
  deleted: true;
};
export type ErrorDetail = Record<string, unknown>;
export type ErrorEnvelope =
{
  error: StructuredError;
};
export type GatewayHealth =
{
  ok: true;
  role: "gateway";
  uptimeSeconds: number;
  rssBytes: number;
};
export type GatewayReadinessDependencies =
{
  manager: ManagerReadiness;
};
export type GatewayReadiness =
{
  ok: boolean;
  role: "gateway";
  dependencies: GatewayReadinessDependencies;
};
export type InboundEnvelope =
{
  deliveryId: string;
  senderExternalId: string;
  conversationExternalId?: string;
  threadExternalId?: string;
  text: string;
  attachmentUrls?: Array<string>;
  receivedAt?: string;
};
export type ManagerReadiness =
{
  ok: boolean;
  role: "manager";
  protocolVersion: "1";
  dependencies: Record<string, ReadinessDependency>;
};
export type MintRunToken =
{
  scopes: Array<string>;
  ttlSeconds?: number;
  agentId?: string;
  workspaceId?: string;
  budgetCeiling?: RunBudgetOverrides;
};
export type MintRunTokenResponse =
{
  token: string;
  tokenId: string;
  expiresAt: string;
  scopes: Array<string>;
  replayPolicy: "resource_bound_multi_use";
};
export type ModelCatalogRecord =
{
  id: string;
  providerId: string;
  capabilities: Array<AgentModelCapability>;
  contextWindow: number;
  inputUsdPerMillion?: number;
  outputUsdPerMillion?: number;
  provenance: "static" | "discovered" | "operator";
};
export type ModelListResponse =
{
  models: Array<ModelCatalogRecord>;
};
export type PublishArtifact =
{
  path: string;
  mediaType: string;
};
export type ProviderConnectionListResponse =
{
  connections: Array<ProviderConnectionRecord>;
};
export type ProviderConnectionLogin =
{
  secret: string;
};
export type ProviderConnectionRecord =
{
  id: string;
  appId: string;
  tenantId: string;
  userId: string;
  providerId: string;
  displayName: string;
  authKind: "api_key" | "oauth" | "delegated_cli" | "local_endpoint";
  credentialProfileId: string;
  baseUrl?: string;
  modelIds: Array<string>;
  status: "needs_login" | "ready" | "error" | "revoked";
  lastErrorCode?: string;
  createdAt: string;
  updatedAt: string;
};
export type RevokeTokenResponse =
{
  tokenId: string;
  revoked: true;
};
export type ReadinessDependency =
{
  ok: boolean;
  reason?: string;
};
export type ResolveApproval =
{
  approved: boolean;
};
export type RunAttemptRecord =
{
  id: string;
  runId: string;
  attempt: number;
  status: "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "ORPHANED";
  startedAt: string;
  endedAt?: string;
};
export type RunAttemptsResponse =
{
  attempts: Array<RunAttemptRecord>;
};
export type RunBudget =
{
  maxTurns: number;
  maxToolCalls: number;
  maxInputTokens: number;
  maxOutputTokens: number;
  maxCostUsd: number;
  totalTimeoutMs: number;
  modelIdleTimeoutMs: number;
  commandTimeoutMs: number;
};
export type RunBudgetOverrides =
{
  maxTurns?: number;
  maxToolCalls?: number;
  maxInputTokens?: number;
  maxOutputTokens?: number;
  maxCostUsd?: number;
  totalTimeoutMs?: number;
  modelIdleTimeoutMs?: number;
  commandTimeoutMs?: number;
};
export type RunEvent =
{
  runId: string;
  sequence: number;
  type: RunEventType;
  payload: ErrorDetail;
  createdAt: string;
};
export type RunEventType = "run.accepted" | "run.queued" | "run.preparing" | "run.started" | "run.snapshot.frozen" | "run.checkpointing" | "run.timed_out" | "run.steered" | "agent.message.delta" | "agent.message.completed" | "tool.call.requested" | "tool.call.completed" | "usage.updated" | "workspace.lease.acquired" | "workspace.lease.released" | "workspace.restore.started" | "workspace.restore.completed" | "workspace.checkpoint.completed" | "workspace.checkpoint.failed" | "approval.requested" | "approval.resolved" | "artifact.created" | "subagent.started" | "subagent.completed" | "run.succeeded" | "run.failed" | "run.cancelled" | "run.orphaned";
export type RunRecord =
{
  id: string;
  idempotencyKey: string;
  appId: string;
  tenantId: string;
  userId: string;
  agentId: string;
  workspaceId: string;
  sessionId?: string;
  parentRunId?: string;
  depth: number;
  deliveryAllowed: boolean;
  input: string;
  budget: RunBudget;
  usage: RunUsage;
  status: RunStatus;
  lastSequence: number;
  errorCode?: string;
  errorMessage?: string;
  createdAt: string;
  updatedAt: string;
};
export type RunStatus = "ACCEPTED" | "QUEUED" | "PREPARING" | "RUNNING" | "CHECKPOINTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "ORPHANED";
export type RunStreamError =
{
  message: string;
};
export type RunStreamFrame = RunEvent | RunStreamError;
export type RunUsage =
{
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  toolCalls: number;
};
export type SessionMessageRecord =
{
  id: string;
  sessionId: string;
  runId?: string;
  role: SessionMessageRole;
  content: string;
  metadata: ErrorDetail;
  createdAt: string;
};
export type SessionMessageRole = "system" | "user" | "assistant" | "tool";
export type SessionMessagesResponse =
{
  messages: Array<SessionMessageRecord>;
};
export type SessionRecord =
{
  id: string;
  appId: string;
  tenantId: string;
  userId: string;
  agentId: string;
  createdAt: string;
  updatedAt: string;
};
export type SteerRun =
{
  instruction: string;
};
export type StructuredError =
{
  version: 1;
  code: string;
  message: string;
  retryable: boolean;
  retryAfterMs?: number;
  details?: ErrorDetail;
};
export type WebhookIngestResponse =
{
  duplicate: boolean;
  runId?: string;
};
export type WorkspaceListResponse =
{
  workspaces: Array<WorkspaceRecord>;
};
export type WorkspaceRecord =
{
  id: string;
  appId: string;
  tenantId: string;
  userId: string;
  mode: "managed" | "registered-bind";
  state: "WARM" | "COLD" | "RESTORING" | "IN_USE" | "SNAPSHOTTING" | "CORRUPT" | "ERROR";
  registeredPath?: string;
  createdAt: string;
  updatedAt: string;
};

export const GENERATED_API_SCHEMAS = [
  "AgentListResponse",
  "AgentModelCapability",
  "AgentProfileRecord",
  "ApprovalRecord",
  "ApprovalStatus",
  "ArtifactPayloadResponse",
  "ArtifactRecord",
  "ChildRunsResponse",
  "CreateAgent",
  "CreateRun",
  "CreateRunResponse",
  "CreateProviderConnection",
  "CreateWorkspace",
  "DeleteProviderConnectionResponse",
  "ErrorDetail",
  "ErrorEnvelope",
  "GatewayHealth",
  "GatewayReadinessDependencies",
  "GatewayReadiness",
  "InboundEnvelope",
  "ManagerReadiness",
  "MintRunToken",
  "MintRunTokenResponse",
  "ModelCatalogRecord",
  "ModelListResponse",
  "PublishArtifact",
  "ProviderConnectionListResponse",
  "ProviderConnectionLogin",
  "ProviderConnectionRecord",
  "RevokeTokenResponse",
  "ReadinessDependency",
  "ResolveApproval",
  "RunAttemptRecord",
  "RunAttemptsResponse",
  "RunBudget",
  "RunBudgetOverrides",
  "RunEvent",
  "RunEventType",
  "RunRecord",
  "RunStatus",
  "RunStreamError",
  "RunStreamFrame",
  "RunUsage",
  "SessionMessageRecord",
  "SessionMessageRole",
  "SessionMessagesResponse",
  "SessionRecord",
  "SteerRun",
  "StructuredError",
  "WebhookIngestResponse",
  "WorkspaceListResponse",
  "WorkspaceRecord"
] as const;
export type GeneratedApiSchemaName = (typeof GENERATED_API_SCHEMAS)[number];
export const GENERATED_API_OPERATIONS = [
  {
    "method": "GET",
    "path": "/healthz",
    "operationId": "getHealthz"
  },
  {
    "method": "POST",
    "path": "/hooks/webhook/{accountId}",
    "operationId": "postHooksWebhookByAccountId"
  },
  {
    "method": "GET",
    "path": "/readyz",
    "operationId": "getReadyz"
  },
  {
    "method": "GET",
    "path": "/v1/agents",
    "operationId": "getV1Agents"
  },
  {
    "method": "POST",
    "path": "/v1/agents",
    "operationId": "postV1Agents"
  },
  {
    "method": "GET",
    "path": "/v1/agents/{agentId}",
    "operationId": "getV1AgentsByAgentId"
  },
  {
    "method": "POST",
    "path": "/v1/approvals/{approvalId}",
    "operationId": "postV1ApprovalsByApprovalId"
  },
  {
    "method": "GET",
    "path": "/v1/artifacts/{artifactId}",
    "operationId": "getV1ArtifactsByArtifactId"
  },
  {
    "method": "GET",
    "path": "/v1/models",
    "operationId": "getV1Models"
  },
  {
    "method": "GET",
    "path": "/v1/provider-connections",
    "operationId": "getV1ProviderConnections"
  },
  {
    "method": "POST",
    "path": "/v1/provider-connections",
    "operationId": "postV1ProviderConnections"
  },
  {
    "method": "DELETE",
    "path": "/v1/provider-connections/{connectionId}",
    "operationId": "deleteV1ProviderConnectionsByConnectionId"
  },
  {
    "method": "POST",
    "path": "/v1/provider-connections/{connectionId}/login",
    "operationId": "postV1ProviderConnectionsByConnectionIdLogin"
  },
  {
    "method": "POST",
    "path": "/v1/runs",
    "operationId": "postV1Runs"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}",
    "operationId": "getV1RunsByRunId"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/artifacts",
    "operationId": "postV1RunsByRunIdArtifacts"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/attempts",
    "operationId": "getV1RunsByRunIdAttempts"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/cancel",
    "operationId": "postV1RunsByRunIdCancel"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/children",
    "operationId": "getV1RunsByRunIdChildren"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/events",
    "operationId": "getV1RunsByRunIdEvents"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/steer",
    "operationId": "postV1RunsByRunIdSteer"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{sessionId}",
    "operationId": "getV1SessionsBySessionId"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{sessionId}/messages",
    "operationId": "getV1SessionsBySessionIdMessages"
  },
  {
    "method": "POST",
    "path": "/v1/tokens",
    "operationId": "postV1Tokens"
  },
  {
    "method": "DELETE",
    "path": "/v1/tokens/{tokenId}",
    "operationId": "deleteV1TokensByTokenId"
  },
  {
    "method": "GET",
    "path": "/v1/workspaces",
    "operationId": "getV1Workspaces"
  },
  {
    "method": "POST",
    "path": "/v1/workspaces",
    "operationId": "postV1Workspaces"
  },
  {
    "method": "GET",
    "path": "/v1/workspaces/{workspaceId}",
    "operationId": "getV1WorkspacesByWorkspaceId"
  }
] as const;
export type GeneratedApiOperation = (typeof GENERATED_API_OPERATIONS)[number];
export type GeneratedApiOperationId = GeneratedApiOperation["operationId"];
