/* Generated by scripts/generate-openapi.ts. Do not edit. */
export type {
  CreateAgentProfileRequest as CreateAgent,
  CreateRunRequest as CreateRun,
  CreateWorkspaceRequest as CreateWorkspace,
  ErrorEnvelope,
  MintRunTokenRequest as MintRunToken,
  MintRunTokenResponse,
  PublishArtifactRequest as PublishArtifact,
  RevokeTokenResponse,
  RunBudgetOverrides,
} from "@lite-harness/contracts";

export const GENERATED_API_OPERATIONS = [
  {
    "method": "GET",
    "path": "/healthz",
    "operationId": "getHealthz"
  },
  {
    "method": "POST",
    "path": "/hooks/webhook/{accountId}",
    "operationId": "postHooksWebhookByAccountId"
  },
  {
    "method": "GET",
    "path": "/readyz",
    "operationId": "getReadyz"
  },
  {
    "method": "GET",
    "path": "/v1/agents",
    "operationId": "getV1Agents"
  },
  {
    "method": "POST",
    "path": "/v1/agents",
    "operationId": "postV1Agents"
  },
  {
    "method": "GET",
    "path": "/v1/agents/{agentId}",
    "operationId": "getV1AgentsByAgentId"
  },
  {
    "method": "POST",
    "path": "/v1/approvals/{approvalId}",
    "operationId": "postV1ApprovalsByApprovalId"
  },
  {
    "method": "GET",
    "path": "/v1/artifacts/{artifactId}",
    "operationId": "getV1ArtifactsByArtifactId"
  },
  {
    "method": "POST",
    "path": "/v1/runs",
    "operationId": "postV1Runs"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}",
    "operationId": "getV1RunsByRunId"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/artifacts",
    "operationId": "postV1RunsByRunIdArtifacts"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/attempts",
    "operationId": "getV1RunsByRunIdAttempts"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/cancel",
    "operationId": "postV1RunsByRunIdCancel"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/children",
    "operationId": "getV1RunsByRunIdChildren"
  },
  {
    "method": "GET",
    "path": "/v1/runs/{runId}/events",
    "operationId": "getV1RunsByRunIdEvents"
  },
  {
    "method": "POST",
    "path": "/v1/runs/{runId}/steer",
    "operationId": "postV1RunsByRunIdSteer"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{sessionId}",
    "operationId": "getV1SessionsBySessionId"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{sessionId}/messages",
    "operationId": "getV1SessionsBySessionIdMessages"
  },
  {
    "method": "POST",
    "path": "/v1/tokens",
    "operationId": "postV1Tokens"
  },
  {
    "method": "DELETE",
    "path": "/v1/tokens/{tokenId}",
    "operationId": "deleteV1TokensByTokenId"
  },
  {
    "method": "GET",
    "path": "/v1/workspaces",
    "operationId": "getV1Workspaces"
  },
  {
    "method": "POST",
    "path": "/v1/workspaces",
    "operationId": "postV1Workspaces"
  },
  {
    "method": "GET",
    "path": "/v1/workspaces/{workspaceId}",
    "operationId": "getV1WorkspacesByWorkspaceId"
  }
] as const;
export type GeneratedApiOperation = (typeof GENERATED_API_OPERATIONS)[number];
export type GeneratedApiOperationId = GeneratedApiOperation["operationId"];
