export const baselineDefects = [
  ["Gateway owner impersonation", "A static bearer token plus caller-controlled tenant and user headers permits owner impersonation; constructed scopes are unenforced."],
  ["Lease renewal and fencing absent", "Workspace leases are acquired once, are not renewed, and fencing epochs are not validated at filesystem or Docker mutation boundaries."],
  ["Provider cleanup defeats hard deadlines", "A non-cooperative provider iterator can hang stream return cleanup and defeat idle and total deadlines."],
  ["Terminal state is not final", "Run terminal state is committed before attempts, side effects, cleanup, checkpointing, and lease release complete."],
  ["Manager shutdown does not drain", "Manager shutdown closes stores without draining or cancelling active runs and child processes."],
  ["Unix Manager split brain", "A second Manager can unlink a live Unix socket and bind the same pathname."],
  ["Plugin version path traversal", "A plugin version containing traversal can move an install outside the configured root and make uninstall remove an out-of-root path."],
  ["Plugin grants are advisory", "Isolated and compatibility plugins are ambient host Node children with HOME, PATH, filesystem, and network authority."],
  ["Browser profile owner collision", "Browser profile storage hashes profile ID without owner, allowing different owners with the same profile name to overwrite one another."],
  ["Session history drops newest messages", "History orders ascending before LIMIT and therefore retains the oldest messages instead of the newest current context."],
  ["Assistant tool calls are not persisted", "Assistant tool-call structure is lost while later tool results remain, producing orphan tool results in provider history."],
  ["Queue wait excluded from total timeout", "The accepted-to-terminal total deadline does not include time spent waiting in a queue."],
  ["Friendly IDs are globally unique", "Agent, workspace, and session slugs are global primary keys instead of owner-scoped external identifiers."],
  ["Idempotency scope and fingerprint are unsafe", "Idempotency uniqueness omits user and fingerprints noncanonical JSON, causing user collisions and equivalent-object conflicts."],
  ["Snapshot identity is unauthenticated", "Snapshot identity metadata is plaintext and not bound as AEAD additional data, allowing relabeling across workspace paths."],
  ["Snapshot rotation can destroy previous-good", "Rotation can replace the known-good previous generation with an unverified corrupt current generation."],
  ["Snapshot pipeline blocks the Manager", "Compression and encryption use whole-buffer synchronous gzip, reads, writes, and Buffer concatenation on the Manager event loop."],
  ["Maintenance containers and archives are unsafe", "Maintenance containers lack consistent hardening, archive validation is incomplete, and export bounds conflict with workspace quota."],
  ["Docker lifecycle is not durable", "Docker uses run --rm without durable object IDs, deterministic names, labels, inspect-before-remove, or startup reconciliation."],
  ["Cancellation cannot guarantee container reap", "Cancellation aborts only the Docker CLI process and has no independent kill and reap guarantee."],
  ["Events and projections are nontransactional", "Usage and tool events, projections, terminal state, and attempt completion span separate transactions and can contradict after a crash."],
  ["SSE and IPC backpressure are unsafe", "Gateway ignores SSE write backpressure, IPC buffers whole large responses, and disconnects do not cancel long polls."],
  ["Readiness permits unusable or fake production", "Readiness can be healthy without Docker, disk, keys, provider, or image and production defaults may silently select fake implementations."],
  ["Migrations are not ordered migrations", "Startup creates the latest schema and marks multiple versions applied instead of executing auditable ordered migrations from old fixtures."],
  ["Delegated runtimes use the wrong workspace", "Delegated Codex and Claude use a process-global host working directory rather than the run's managed leased workspace."],
  ["Claude leaks prompts through argv", "Claude conversation content is passed in process arguments and is visible in process listings."],
  ["Process RPC cancellation and bounds are incomplete", "Timeout does not cancel remote side effects, partial stdout is unbounded, abort listeners leak, child HOME is ambient, and pre-aborted calls can spawn."],
  ["Approval decisions are not immutably bound", "Approvals lack a digest binding exact arguments, owner, workspace, route and policy generation, and expiry at resolution and execution."],
  ["Tool arguments bypass advertised schemas", "Tool arguments are not generically validated against the exact advertised schema before dispatch."],
  ["Unknown model price bypasses cost ceilings", "Unknown prices and omitted adapter cost allow maxCostUsd constraints to pass without enforceable cost accounting."],
  ["Fallback can repeat visible work", "Fallback visibility ignores usage events and can double count or repeat unsafe work after partial visibility."],
  ["OpenAI Responses is missing", "OpenAI uses chat completions rather than a first-class Responses adapter and exposes shallow capability, error, and usage semantics."],
  ["Anthropic can send credentials over plaintext", "Endpoint policy may allow a nonloopback plaintext HTTP Anthropic origin and transmit a credential."],
  ["Registered binds accept sensitive roots", "Registered bind validation does not reject filesystem root, user home, or sensitive system directories and lacks portable path rules."],
  ["Artifact publication trusts model content", "artifact_publish accepts model-supplied bytes rather than an authorized workspace path and stores plain nontransactional files and metadata."],
  ["Webhook signatures verify reserialized JSON", "Signature verification uses parsed and reserialized JSON instead of the exact raw request bytes."],
  ["Boundary schemas are inconsistent", "Manager and public validation are incomplete and internal requests do not reuse authoritative versioned schemas."],
  ["Optional systems are disconnected libraries", "Plugins, skills, MCP, context, snapshot compaction, and cache catalog are not composed through the production Manager and run loop."],
  ["Model routing ignores stored capabilities", "Routing is a single startup route requiring only text; agent capabilities and durable route and usage decisions are ignored."],
  ["Coding harness lacks essential tools", "The coding harness has only read and write file tools and lacks bounded shell, search, patch, git, test, build, package, process, and artifact tools."],
  ["Tool image contradicts the coding profile", "The Alpine BusyBox image lacks the required Debian or glibc base, certificates, init, shell, git, Node package tooling, and optional Python profiles."],
  ["Browser egress is inside the compromise boundary", "Browser network enforcement shares a networked container with Chromium and can be bypassed by a browser or container compromise."],
  ["Browser durability and artifact flows are disconnected", "Browser action, audit, session, and profile state is not durable and uploads or downloads use memory or base64 instead of authorized artifact promotion."],
  ["Skills are eager and mutable in practice", "Skill bodies load eagerly and precedence, provenance, versions, bounds, gating, and immutable run snapshots are incomplete."],
  ["MCP workers have ambient host authority", "MCP children are host processes outside normal tool policy with incomplete schema, payload, cancellation, and failure isolation."],
  ["Cache catalog has no real cache lifecycle", "Cache metadata and directories exist without staged population, verification, read-only attach, leases, scope, eviction, or garbage collection."],
  ["Snapshot lifecycle is manual", "Runs do not automatically prepare, restore, dirty-track, checkpoint, verify, transition cold, or delete volumes."],
  ["Immutable RunSnapshot is absent", "Runs do not freeze agent, tools, skills, plugins, provider route, runtime profile, network policy, budgets, and credential profile IDs."],
  ["Disabled packs do not prove zero overhead", "Optional packs are statically imported or installed and disabled mode does not prove zero workers, timers, sockets, schemas, containers, or dependencies."],
  ["pxpipe evidence is disconnected and tautological", "Context optimization is disconnected, has pin conflict, stores exact content only in memory, and lacks paired model-quality evidence."],
  ["Build emits no applications", "Root build runs tsc with no emit and produces no compiled Gateway, Manager, launcher, CLI, or distributable application."],
  ["TypeScript SDK is not installable", "The SDK is private raw TypeScript with workspace-only contracts and its packed output does not run in a clean Node project."],
  ["Python SDK evidence is mocked only", "Python validation is limited to mocked urllib unit tests instead of installed wheel and sdist parity against a real Gateway."],
  ["Gateway-to-Manager E2E bypasses IPC", "The existing E2E substitutes in-process ManagerTransport and bypasses processes, SDK, Docker, packaging, and restart."],
  ["Required real tests silently skip", "Docker, Chromium, and provider tests skip unless optional environment variables are manually supplied."],
  ["Candidate image digest is never executed", "The image workflow publishes manifests without running the exact candidate digest that is promoted."],
  ["Release validation is presence-based", "Release checks validate strings and parseability rather than OpenAPI semantics, drift, installability, and alpha behavior."],
  ["Cross-platform product evidence is absent", "There is no real rootless Linux, Docker Desktop macOS and Windows, daemon restart, sleep and resume, offline, or scale-zero evidence."],
  ["Doctor misses required failures", "Doctor exit status ignores bad registered mounts, DB lock or corruption, keys, Docker context, image, migrations, and complete IPC health."],
  ["CLI and service flow executes source", "Services use tsx source, Windows task creation does not prove start, and fake runtime or provider defaults can appear ready."],
  ["OpenAPI is incomplete and not authoritative", "OpenAPI is not complete, generated from authoritative schemas, or used to generate and check SDK models."],
  ["Metrics, audit, trace, and config validation are incomplete", "Observability is incomplete while logs may leak details and numeric or environment config accepts NaN and unsafe values."],
  ["Architecture and status documentation overclaim", "Narrative architecture and implementation status claim disconnected or unverified product behavior."],
  ["Public naming remains unresolved", "Public npm, PyPI, GitHub, container, domain, and trademark naming has no owner-approved collision decision."],
];

export function createDefectLedger() {
  return baselineDefects.map(([title, description], index) => {
    const number = index + 1;
    return {
      id: `BD-${String(number).padStart(3, "0")}`,
      title,
      description,
      severity: number <= 8 ? "critical" : "high",
      category: number <= 8 ? "lifecycle-trust-boundary" : number <= 37 ? "correctness-isolation" : number <= 50 ? "integration" : "packaging-operations-evidence",
      source: { document: "goal-mission", section: `Known baseline defects / ${number}`, baselineCommit: "f9d522289b500174e4e387b6078f907ea4ac56fa" },
      status: "open",
      reproduction: { testId: `BD-${String(number).padStart(3, "0")}-REPRO`, path: null, result: "not-run", evidenceArtifact: null },
      regression: { testId: `BD-${String(number).padStart(3, "0")}-REGRESSION`, path: null, result: "not-run", evidenceArtifact: null },
      fixCommits: [],
      blockers: ["baseline-reproduction-required"],
    };
  });
}
