import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const ledger = JSON.parse(readFileSync(resolve(root, "docs", "requirements", "alpha-ledger.yaml"), "utf8"));
const defects = JSON.parse(readFileSync(resolve(root, "docs", "requirements", "defect-ledger.yaml"), "utf8"));
const output = resolve(root, "docs", "IMPLEMENTATION_STATUS.md");
const rendered = render();
if (process.argv.includes("--check")) {
  const current = readFileSync(output, "utf8").replaceAll("\r\n", "\n");
  if (current !== rendered) {
    process.stderr.write("docs/IMPLEMENTATION_STATUS.md is stale; run pnpm generate:status.\n");
    process.exitCode = 1;
  } else process.stdout.write("Generated implementation status is current.\n");
} else {
  writeFileSync(output, rendered);
  process.stdout.write("Generated docs/IMPLEMENTATION_STATUS.md from requirement and defect evidence.\n");
}

function render() {
  const requirements = ledger.requirements;
  const counts = countBy(requirements, "status");
  const openDefects = defects.defects.filter((defect) => defect.status !== "closed");
  const verified = requirements.every((row) => row.status === "verified" && row.blockers.length === 0) && openDefects.length === 0;
  const lines = [
    "# Implementation status", "",
    "> Generated by `pnpm generate:status` from the requirement and defect ledgers. Do not edit claims by hand.", "",
    `Baseline reviewed: \`${ledger.baseline.commit}\` on \`${ledger.baseline.branch}\`.`,
    `Architecture contract SHA-256: \`${ledger.baseline.architectureContractSha256}\`.`, "",
    `## Verdict: ${verified ? "VERIFIED ALPHA" : "NOT YET A VERIFIED ALPHA"}`, "",
    verified
      ? "Every required row has current zero-skip evidence and no blocker/high defect remains."
      : "The repository is a pre-alpha work in progress. A file, class, unit test, or prior green workflow is not treated as proof of an integrated product requirement.",
    "", "## Requirement ledger", "",
    `- Total required rows: ${requirements.length}`,
    `- Verified: ${counts.verified ?? 0}`,
    `- In progress: ${counts["in-progress"] ?? 0}`,
    `- Blocked or unverified: ${counts.blocked ?? 0}`,
    "", "| Kind | Total | Verified |", "| --- | ---: | ---: |",
  ];
  for (const kind of ["frozen-decision", "phase-exit", "alpha-gate", "contract-requirement"]) {
    const rows = requirements.filter((row) => row.kind === kind);
    lines.push(`| ${kind} | ${rows.length} | ${rows.filter((row) => row.status === "verified").length} |`);
  }
  lines.push("", "## Alpha gates", "", "| Gate | Status | Current blocker |", "| --- | --- | --- |");
  for (const row of requirements.filter((item) => item.kind === "alpha-gate")) {
    lines.push(`| ${row.id} ${escapeCell(row.title)} | ${row.status} | ${escapeCell(row.blockers.join(", ") || "none")} |`);
  }
  lines.push("", "## Roadmap exits", "", "| Phase | Status | Current blocker |", "| --- | --- | --- |");
  for (const row of requirements.filter((item) => item.kind === "phase-exit")) {
    lines.push(`| ${row.id} ${escapeCell(row.title)} | ${row.status} | ${escapeCell(row.blockers.join(", ") || "none")} |`);
  }
  const severity = countBy(openDefects, "severity");
  lines.push("", "## Open release-blocking defects", "", `- Critical: ${severity.critical ?? 0}`, `- High: ${severity.high ?? 0}`, "",
    "The authoritative details, reproduction IDs, regression IDs, fix commits, and evidence references are in `docs/requirements/defect-ledger.yaml`.", "",
    "## Evidence policy", "",
    "A row becomes verified only when it maps to production paths, runnable test IDs, a required CI job, and evidence captured for the current commit with `result: pass` and `skips: 0`. External platform, provider, naming, signing, and registry gates remain blockers until their exact evidence exists.");
  return `${lines.join("\n")}\n`;
}

function countBy(rows, field) {
  return rows.reduce((counts, row) => ({ ...counts, [row[field]]: (counts[row[field]] ?? 0) + 1 }), {});
}

function escapeCell(value) { return String(value).replaceAll("|", "\\|").replaceAll("\n", " "); }
