import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { currentCommit, currentTree, evaluateReleaseTruth } from "./release-truth-lib.mjs";

const root = resolve(import.meta.dirname, "..");
const ledger = JSON.parse(readFileSync(resolve(root, "docs", "requirements", "alpha-ledger.yaml"), "utf8"));
const defects = JSON.parse(readFileSync(resolve(root, "docs", "requirements", "defect-ledger.yaml"), "utf8"));
const head = currentCommit(root);
const tree = currentTree(root, head);
const output = resolve(root, "docs", "IMPLEMENTATION_STATUS.md");
const rendered = render();
if (process.argv.includes("--check")) {
  const current = readFileSync(output, "utf8").replaceAll("\r\n", "\n");
  if (current !== rendered) {
    process.stderr.write("docs/IMPLEMENTATION_STATUS.md is stale; run pnpm generate:status.\n");
    process.exitCode = 1;
  } else process.stdout.write("Generated implementation status is current.\n");
} else {
  writeFileSync(output, rendered);
  process.stdout.write("Generated docs/IMPLEMENTATION_STATUS.md from requirement and defect evidence.\n");
}

function render() {
  const requirements = ledger.requirements;
  const alphaRequirements = requirements.filter((row) => row.required === true);
  const declaredCounts = countBy(alphaRequirements, "status");
  const { requirementEvaluations: evaluatedRequirements, defectEvaluations } = evaluateReleaseTruth({
    requirements,
    defects: defects.defects,
  }, { root, head, tree });
  const currentVerified = evaluatedRequirements.filter((item) => item.row.required === true && item.verified);
  const openDefects = defectEvaluations.filter((item) => !item.closed).map((item) => item.defect);
  const unprovenClosures = defectEvaluations
    .filter((item) => item.defect.status === "closed" && !item.closed);
  const verified = currentVerified.length === alphaRequirements.length && openDefects.length === 0 && unprovenClosures.length === 0;
  const lines = [
    "# Implementation status", "",
    "> Generated by `pnpm generate:status` from the requirement and defect ledgers. Do not edit claims by hand.", "",
    `Baseline reviewed: \`${ledger.baseline.commit}\` on \`${ledger.baseline.branch}\`.`,
    `Architecture contract SHA-256: \`${ledger.baseline.architectureContractSha256}\`.`, "",
    `## Verdict: ${verified ? "VERIFIED ALPHA" : "NOT YET A VERIFIED ALPHA"}`, "",
    verified
      ? "Every required row has current zero-skip evidence and no blocker/high defect remains."
      : "The repository is a pre-alpha work in progress. A file, class, unit test, or prior green workflow is not treated as proof of an integrated product requirement.",
    "", "## Requirement ledger", "",
    `- Total ledger rows: ${requirements.length}`,
    `- Alpha-required rows: ${alphaRequirements.length}`,
    `- Verified by current zero-skip evidence: ${currentVerified.length}`,
    `- Declared verified in the ledger: ${declaredCounts.verified ?? 0}`,
    `- Declared in progress: ${declaredCounts["in-progress"] ?? 0}`,
    `- Currently blocked or unverified alpha rows: ${alphaRequirements.length - currentVerified.length}`,
    `- Non-alpha rows retained in ledger: ${requirements.length - alphaRequirements.length}`,
    "", "| Tier | Ledger rows | Alpha-required | Current evidence |", "| --- | ---: | ---: | ---: |",
    ...["alpha", "preview", "beta", "future"].map((tier) => {
      const rows = requirements.filter((row) => row.tier === tier);
      const current = evaluatedRequirements.filter((item) => item.row.tier === tier && item.verified).length;
      return `| ${tier} | ${rows.length} | ${rows.filter((row) => row.required).length} | ${current} |`;
    }),
    "", "| Kind | Total | Current evidence | Declared verified |", "| --- | ---: | ---: | ---: |",
  ];
  for (const kind of ["frozen-decision", "phase-exit", "alpha-gate", "contract-requirement"]) {
    const rows = alphaRequirements.filter((row) => row.kind === kind);
    const current = currentVerified.filter((item) => item.row.kind === kind).length;
    lines.push(`| ${kind} | ${rows.length} | ${current} | ${rows.filter((row) => row.status === "verified").length} |`);
  }
  lines.push("", "## Alpha gates", "", "| Gate | Status | Current blocker |", "| --- | --- | --- |");
  for (const row of requirements.filter((item) => item.kind === "alpha-gate")) {
    const evaluation = evaluatedRequirements.find((item) => item.row.id === row.id);
    const status = evaluation.verified ? "verified" : row.status === "verified" ? "unverified" : row.status;
    const blocker = row.blockers.join(", ") || evaluation.failures[0] || "unverified";
    lines.push(`| ${row.id} ${escapeCell(row.title)} | ${status} | ${escapeCell(blocker)} |`);
  }
  lines.push("", "## Roadmap exits", "", "| Phase | Status | Current blocker |", "| --- | --- | --- |");
  for (const row of requirements.filter((item) => item.kind === "phase-exit")) {
    const evaluation = evaluatedRequirements.find((item) => item.row.id === row.id);
    const status = evaluation.verified ? "verified" : row.status === "verified" ? "unverified" : row.status;
    const blocker = row.blockers.join(", ") || evaluation.failures[0] || "unverified";
    lines.push(`| ${row.id} ${escapeCell(row.title)} | ${status} | ${escapeCell(blocker)} |`);
  }
  const severity = countBy(openDefects, "severity");
  const unprovenSeverity = countBy(unprovenClosures.map((item) => item.defect), "severity");
  lines.push("", "## Open release-blocking defects", "", `- Critical: ${severity.critical ?? 0}`, `- High: ${severity.high ?? 0}`, "",
    "## Defect closures lacking current evidence", "", `- Critical: ${unprovenSeverity.critical ?? 0}`, `- High: ${unprovenSeverity.high ?? 0}`, "",
    "The authoritative details, reproduction IDs, regression IDs, fix commits, and evidence references are in `docs/requirements/defect-ledger.yaml`.", "",
    "## Evidence policy", "",
    "A row becomes verified only when it maps to production paths, runnable test IDs, a required CI job, and evidence captured for the current commit with `result: pass` and `skips: 0`. External platform, provider, naming, signing, and registry gates remain blockers until their exact evidence exists.");
  return `${lines.join("\n")}\n`;
}

function countBy(rows, field) {
  return rows.reduce((counts, row) => ({ ...counts, [row[field]]: (counts[row[field]] ?? 0) + 1 }), {});
}

function escapeCell(value) { return String(value).replaceAll("|", "\\|").replaceAll("\n", " "); }
